module.exports = {
    catch_all: /microsoft|google|amazon|amzn|aws|red hat|redhat|ibm|pivotal|intel|facebook|alibaba|uber|wix|github|tencent|baidu|apple|mozilla|oracle|shopify|mongodb|vmware|netflix|salesforce|linkedin|palantir|yahoo|mapbox|unity|automattic|travis|spotify|zalando|esri|sap|epam|telerik|stripe|kitware|suse|odoo|yandex|adobe|airbnb|guardian|docker|nuxeo|nvidia|elastic|yelp|wso2|inria|puppet|datadog|jetbrains|canonical|rackspace|thoughtworks/gi,
    map: {
        microsoft: 'Microsoft',
        google: 'Google',
        amazon: 'Amazon',
        amzn: 'Amazon',
        aws: 'Amazon',
        'red hat': 'Red Hat',
        redhat: 'Red Hat',
        ibm: 'IBM',
        pivotal: 'Pivotal',
        intel: 'Intel',
        facebook: 'Facebook',
        alibaba: 'Alibaba',
        uber: 'Uber',
        wix: 'WIX',
        github: 'GitHub',
        tencent: 'Tencent',
        baidu: 'Baidu',
        apple: 'Apple',
        mozilla: 'Mozilla',
        oracle: 'Oracle',
        shopify: 'Shopify',
        mongodb: 'MongoDB',
        vmware: 'VMWare',
        netflix: 'Netflix',
        salesforce: 'Salesforce',
        linkedin: 'LinkedIn',
        palantir: 'Palantir Technologies',
        yahoo: 'Yahoo!',
        mapbox: 'Mapbox',
        unity: 'Unity Technologies',
        automattic: 'Automattic',
        travis: 'Travis CI',
        spotify: 'Spotify',
        zalando: 'Zalando DE',
        esri: 'ESRI',
        sap: 'SAP SE',
        epam: 'EPAM Systems',
        telerik: 'Telerik',
        stripe: 'Stripe',
        kitware: 'Kitware',
        suse: 'SUSE',
        odoo: 'Odoo',
        yandex: 'Yandex',
        adobe: 'Adobe Systems',
        airbnb: 'Airbnb',
        guardian: 'The Guardian',
        docker: 'Docker',
        nuxeo: 'Nuxeo',
        nvidia: 'NVIDIA',
        elastic: 'Elastic',
        yelp: 'Yelp',
        wso2: 'WSO2',
        inria: 'INRIA',
        puppet: 'Puppet Labs',
        datadog: 'DataDog',
        jetbrains: 'JetBrains',
        canonical: 'Canonical',
        rackspace: 'Rackspace',
        thoughtworks: 'ThoughtWorks'
    }
};
